
# Find top 10 and bottom 10 product categories by order volume and total sales value

# Top categories like Bed/Bath and Health & Beauty drive nearly 10,000 orders each, whereas niche categories like PC Gaming and CDs generate under 15 orders total. Strategic focus should be placed on high-AOV drivers like Watches & Beauty

WITH product_details AS (
  SELECT 
    p.`product category` AS product_category,
    COUNT(DISTINCT oi.order_id) AS order_volume,
    ROUND(SUM(oi.price), 2) AS total_sales_value
  FROM `TARGET_SQL.products` p
  JOIN `TARGET_SQL.order_items` oi ON p.product_id = oi.product_id
  WHERE p.`product category` IS NOT NULL
  GROUP BY p.`product category`  
),
top_10 AS (
  SELECT
    product_category AS top_product_category,
    order_volume,
    total_sales_value,
    ROW_NUMBER() OVER (ORDER BY order_volume DESC) AS rn
  FROM product_details
  LIMIT 10
),
bottom_10 AS (
  SELECT
    product_category AS bottom_product_category,
    order_volume,
    total_sales_value,
    ROW_NUMBER() OVER (ORDER BY order_volume ASC) AS rn
  FROM product_details
  LIMIT 10
)
SELECT
  t.top_product_category,
  t.order_volume,
  t.total_sales_value,
  b.bottom_product_category,
  b.order_volume,
  b.total_sales_value
FROM top_10 t
JOIN bottom_10 b ON t.rn = b.rn
ORDER BY t.rn;


# Identify what percentage of total marketplace revenue is generated by the Top 5% of active sellers

# Top 5% of sellers account for around 53% of the overall revenue which highlights a heavy seller-concentration risk

WITH seller_details AS (
  SELECT 
    seller_id,
    SUM(price) AS total_revenue
  FROM `TARGET_SQL.order_items`
  GROUP BY seller_id  
),
ranked_sellers AS (
  SELECT 
    seller_id,
    total_revenue,
    -- Divide sellers into 100 percentile buckets based on revenue
    NTILE(100) OVER (ORDER BY total_revenue DESC) AS percentile_bucket
  FROM seller_details
)

SELECT 
  -- Calculate the percentage share
  ROUND(SUM(CASE WHEN percentile_bucket <= 5 THEN total_revenue ELSE 0 END) * 100.0 / SUM(total_revenue), 2) AS top_5_percent_revenue_share
FROM ranked_sellers;





